export type PoolKey="s-pow"|"s-tec"|"b-c-d";
export type PoolCard={cardSlug:string;name:string;rate:string;rank:string};
export type Duelist={slug:string;name:string;initial:string;location:string;deck:string;order:number;bestRank?:string;about?:string;farmTip?:string;farmGuide?:string;heroImage?:string;squareImage?:string;bio:string;answer:string;pools:Record<PoolKey,PoolCard[]>;faq:Array<{q:string;a:string}>};
export const duelists:Duelist[]=[
 {slug:"heishin",name:"Heishin",initial:"H",location:"Coliseu",deck:"Deck de Heishin",order:31,bio:"Sacerdote de grande poder e um dos oponentes mais procurados por jogadores que buscam cartas raras.",answer:"Heishin é um duelista de fim de campanha indicado para farms ofensivos. Priorize vitórias em Rank S/A POW e registre séries de duelos para comparar resultados.",pools:{"s-pow":[{cardSlug:"meteor-b-dragon",name:"Meteor B. Dragon",rate:"0,10%",rank:"S/A POW"},{cardSlug:"megamorph",name:"Megamorph",rate:"0,05%",rank:"S/A POW"},{cardSlug:"blue-eyes-white-dragon",name:"Blue-Eyes White Dragon",rate:"em validação",rank:"S/A POW"}],"s-tec":[{cardSlug:"dark-magician",name:"Dark Magician",rate:"em validação",rank:"S/A TEC"}],"b-c-d":[{cardSlug:"gate-guardian",name:"Gate Guardian",rate:"em validação",rank:"B/C/D"}]},faq:[{q:"O que Heishin dropa?",a:"O catálogo inicial reúne Meteor B. Dragon, Megamorph, Blue-Eyes White Dragon, Dark Magician e Gate Guardian em faixas diferentes."},{q:"Qual rank usar contra Heishin?",a:"Use S/A POW para o farm ofensivo e S/A TEC quando a carta estiver na bolsa técnica."}]},
 {slug:"seto-3rd",name:"Seto 3rd",initial:"S",location:"Final do jogo",deck:"Deck de Seto 3rd",order:37,bio:"Uma das versões mais fortes de Seto e fonte importante de monstros de alto ataque.",answer:"Seto 3rd é indicado para quem já possui um deck consistente de fim de jogo.",pools:{"s-pow":[{cardSlug:"blue-eyes-white-dragon",name:"Blue-Eyes White Dragon",rate:"0,05%",rank:"S/A POW"},{cardSlug:"meteor-b-dragon",name:"Meteor B. Dragon",rate:"em validação",rank:"S/A POW"}],"s-tec":[],"b-c-d":[]},faq:[{q:"Seto 3rd dropa Blue-Eyes?",a:"Sim. O catálogo local registra Blue-Eyes White Dragon na faixa S/A POW."}]},
 {slug:"nitemare",name:"Nitemare",initial:"N",location:"Duelo final",deck:"Deck de Nitemare",order:39,bio:"Oponente final com uma das bolsas mais cobiçadas do jogo.",answer:"Nitemare exige um deck de alto poder e boa consistência para farms longos.",pools:{"s-pow":[{cardSlug:"blue-eyes-white-dragon",name:"Blue-Eyes White Dragon",rate:"0,05%",rank:"S/A POW"},{cardSlug:"gate-guardian",name:"Gate Guardian",rate:"em validação",rank:"S/A POW"}],"s-tec":[],"b-c-d":[]},faq:[{q:"Vale a pena farmar Nitemare?",a:"Sim, quando seu deck já vence com consistência e você busca cartas de fim de jogo."}]},
 {slug:"pegasus",name:"Pegasus",initial:"P",location:"Castelo de Pegasus",deck:"Deck Toon",order:18,bio:"Duelista com cartas mágicas e monstros peculiares.",answer:"Pegasus é uma opção intermediária para diversificar o catálogo e treinar controle de duelo.",pools:{"s-pow":[{cardSlug:"megamorph",name:"Megamorph",rate:"em validação",rank:"S/A POW"}],"s-tec":[],"b-c-d":[]},faq:[{q:"Qual o melhor rank contra Pegasus?",a:"Depende da carta: confirme a bolsa antes de escolher entre POW e TEC."}]},
 {slug:"yami-bakura",name:"Yami Bakura",initial:"B",location:"Campanha",deck:"Deck das Trevas",order:12,bio:"Duelista focado em criaturas sombrias e estratégias de controle.",answer:"Yami Bakura é útil para buscar cartas de atributo Dark durante a progressão.",pools:{"s-pow":[{cardSlug:"dark-magician",name:"Dark Magician",rate:"em validação",rank:"S/A POW"}],"s-tec":[],"b-c-d":[]},faq:[{q:"Yami Bakura dropa cartas Dark?",a:"O catálogo inicial registra Dark Magician; outras taxas aguardam validação."}]},
 {slug:"weevil-underwood",name:"Weevil Underwood",initial:"W",location:"Campanha",deck:"Deck de Insetos",order:8,bio:"Especialista em insetos e um dos primeiros farms temáticos da campanha.",answer:"Weevil Underwood é indicado para cartas de Inseto e para melhorar o deck no começo da campanha.",pools:{"s-pow":[],"s-tec":[],"b-c-d":[]},faq:[{q:"Quando enfrentar Weevil Underwood?",a:"Ele aparece durante a progressão inicial e pode ser repetido no Free Duel."}]},
];
export const getDuelist=(slug:string)=>duelists.find(item=>item.slug===slug);

export type ModRecord={slug:string;name:string;version:string;author:string;tag:string;multiplier:string;summary:string;content?:string;image?:string;sourceUrl?:string;features:string[];changelog:string[];faq:Array<{q:string;a:string}>};
export const mods:ModRecord[]=[
 {slug:"mod-15-drop-x15",name:"Forbidden Memories Mod 15",version:"15",author:"Comunidade FM",tag:"Drop x15",multiplier:"x15",summary:"Versão voltada a reduzir o tempo de farm e acelerar a montagem de decks.",features:["Taxas de drop ampliadas","Progressão mais rápida","Compatibilidade sujeita à versão do patch"],changelog:["Ajustes nas bolsas de recompensa","Rebalanceamento de progressão","Correções comunitárias"],faq:[{q:"O site hospeda o Mod 15?",a:"Não. O portal apenas documenta o projeto e aponta para canais externos validados."},{q:"Preciso da ROM original?",a:"Use somente uma cópia obtida legalmente e siga as instruções do autor do patch."}]},
 {slug:"forbidden-memories-perfect",name:"Forbidden Memories Perfect",version:"Atual",author:"Comunidade FM",tag:"Perfect",multiplier:"Variável",summary:"Projeto que expande cartas, equilíbrio e desafios mantendo a base clássica.",features:["Novos desafios","Decks revisados","Conteúdo expandido"],changelog:["Versões variam conforme o mantenedor"],faq:[{q:"Perfect é o mesmo que o jogo original?",a:"Não. É uma modificação comunitária e pode alterar drops, decks e progressão."}]},
 {slug:"forbidden-memories-remaster",name:"Forbidden Memories Remaster",version:"Comunidade",author:"Autores independentes",tag:"Remaster",multiplier:"Padrão",summary:"Nome usado por projetos que modernizam apresentação e qualidade de vida.",features:["Melhorias visuais","Ajustes de interface","Compatibilidade dependente do projeto"],changelog:["Consulte sempre a publicação original do autor"],faq:[{q:"Existe um único Remaster oficial?",a:"Não. Confirme autor, versão e origem antes de aplicar qualquer patch."}]},
];
export const getMod=(slug:string)=>mods.find(item=>item.slug===slug);

export type GuideRecord={slug:string;title:string;category:string;excerpt:string;intro:string;steps:Array<{title:string;text:string}>;faq:Array<{q:string;a:string}>};
export const guides:GuideRecord[]=[
 {slug:"como-conseguir-s-pow",title:"Como conseguir S-POW",category:"Rank",excerpt:"Vitórias rápidas e ofensivas para acessar a bolsa S/A POW.",intro:"S-POW recompensa desempenho ofensivo: poucos turnos, alto dano e vitória direta.",steps:[{title:"Monte um deck consistente",text:"Use fusões repetíveis e cartas que evitem mãos travadas."},{title:"Vença em poucos turnos",text:"Reduza ações sem impacto e finalize assim que houver dano suficiente."},{title:"Preserve seus pontos de vida",text:"Evite trocas desnecessárias e mantenha vantagem até o golpe final."}],faq:[{q:"Quantos turnos devo usar?",a:"Não existe um único número isolado; o rank considera o conjunto do desempenho."}]},
 {slug:"como-conseguir-s-tec",title:"Como conseguir S-TEC",category:"Rank",excerpt:"Controle o duelo, use recursos variados e acumule pontuação técnica.",intro:"S-TEC exige uma partida longa e controlada, com uso amplo do deck.",steps:[{title:"Controle o oponente",text:"Mantenha defesa segura enquanto prolonga o duelo."},{title:"Use magias e armadilhas",text:"Variedade de ações ajuda a construir pontuação técnica."},{title:"Evite finalizar cedo",text:"O objetivo é demonstrar uso técnico, não velocidade."}],faq:[{q:"S-TEC serve para as mesmas cartas?",a:"Não. Cada faixa possui uma bolsa de recompensas diferente."}]},
 {slug:"melhores-fusoes",title:"Melhores fusões para avançar",category:"Fusões",excerpt:"Combinações acessíveis para melhorar o deck sem depender de cartas raras.",intro:"Fusões consistentes são o caminho mais seguro para vencer a campanha inicial.",steps:[{title:"Dragon + Thunder",text:"Uma das linhas mais conhecidas para alcançar Twin-Headed Thunder Dragon."},{title:"Warrior + Beast",text:"Opção acessível para gerar atacantes intermediários."},{title:"Teste no Free Duel",text:"Valide combinações sem interromper a progressão principal."}],faq:[{q:"Qual é a melhor fusão inicial?",a:"A melhor é a que seu deck consegue repetir; consistência importa mais que um pico isolado."}]},
 {slug:"como-montar-deck",title:"Como montar um deck consistente",category:"Deck",excerpt:"Equilibre monstros, equipamentos e linhas de fusão.",intro:"Um deck consistente reduz mãos sem jogada e melhora tanto campanha quanto farm.",steps:[{title:"Escolha uma linha principal",text:"Defina um tipo ou fusão que apareça com frequência."},{title:"Reduza cartas situacionais",text:"Evite cartas que dependam de uma única combinação rara."},{title:"Inclua equipamentos",text:"Use equipamentos compatíveis com seus principais atacantes."}],faq:[{q:"Quantas cartas fortes preciso?",a:"Menos do que parece: fusões consistentes compensam a ausência de raridades."}]},
];
export const getGuide=(slug:string)=>guides.find(item=>item.slug===slug);
