import type { Metadata } from "next";
import { headers } from "next/headers";
import "../../exact-card.css";
import { cards as localCards } from "../../../lib/catalog";
import { getCard, getCards, getDuelists } from "../../../lib/data";
import { cardImageSources as cardImages, getCardImage } from "../../../lib/card-images";
import { taxonomySlug } from "../../../lib/wordpress-data";
import { CardVisual } from "../../components/card-visual";
import { CopyPassword } from "../../components/copy-password";

type PageProps={params:Promise<{slug:string}>};

const siteOrigin=(process.env.SITE_URL||"https://yugiohforbiddenmemories.com").replace(/\/$/,"");
const siteUrl=(path:string)=>`${siteOrigin}${path.startsWith("/")?path:`/${path}`}`;
const datasetCreator={"@type":"Organization",name:"Yu-Gi-Oh! Forbidden Memories",url:siteOrigin};
const datasetLicense="https://creativecommons.org/licenses/by/4.0/";

export function generateStaticParams(){return localCards.map(card=>({slug:card.slug}))}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const card=await getCard((await params).slug);if(!card)return{title:"Carta não encontrada | Yu-Gi-Oh! Forbidden Memories"};const title=`${card.name}: drops, password e stats | Yu-Gi-Oh! Forbidden Memories`;const description=`${card.name} (#${String(card.id).padStart(3,"0")}): password ${card.password}, ${card.atk} ATK, ${card.def} DEF e onde conseguir em Forbidden Memories.`;const image=getCardImage(card.slug);const requestHeaders=await headers();const host=requestHeaders.get("x-forwarded-host")||requestHeaders.get("host")||"localhost:3000";const protocol=requestHeaders.get("x-forwarded-proto")||(host.startsWith("localhost")?"http":"https");const imageSource=card.image||image?.src;const socialImage=imageSource?new URL(imageSource,`${protocol}://${host}`).toString():`${protocol}://${host}/og.png`;return{title,description,openGraph:{title,description,siteName:"Yu-Gi-Oh! Forbidden Memories",images:[{url:socialImage,width:image?.width,height:image?.height,alt:`Carta ${card.name}`}]},twitter:{card:"summary_large_image",title,description,images:[socialImage]}}}

export default async function CardPage({params}:PageProps){
  const card=await getCard((await params).slug);if(!card)return <main className="not-found"><p>404</p><h1>Carta não encontrada</h1><a href="/cartas/">Voltar para as cartas</a></main>;
  const [cards,duelists]=await Promise.all([getCards(),getDuelists()]);const index=cards.findIndex(item=>item.slug===card.slug);const previous=cards[(index-1+cards.length)%cards.length];const next=cards[(index+1)%cards.length];const duelistsBySlug=new Map(duelists.map(duelist=>[duelist.slug,duelist]));
  const drops=card.drops;
  const related=cards.filter(item=>item.slug!==card.slug&&(item.type===card.type||item.attribute===card.attribute)).slice(0,6);
  const faq=[{q:`Quem dropa o ${card.name}?`,a:drops.length?`${drops.map(drop=>`${drop.duelist} (${drop.rate})`).join(", ")}. Consulte a faixa de rank indicada antes de farmar.`:"Os dados de drop desta carta ainda estão em validação."},{q:`Qual o password do ${card.name}?`,a:`O password é ${card.password}. Use na opção Password do jogo para localizar a carta.`},{q:`Como conseguir o ${card.name} mais rápido?`,a:drops.length?`Compare as taxas e priorize ${[...drops].sort((a,b)=>parseFloat(b.rate.replace(",","."))-parseFloat(a.rate.replace(",",".")))[0].duelist}, buscando Rank S na faixa indicada.`:"Use o password ou aguarde a validação das taxas de drop."}];
  const dateModified="2026-08-18";const formattedPassword=`${card.password.slice(0,4)} ${card.password.slice(4)}`;
  const cardUrl=siteUrl(`/cartas/${card.slug}/`);const cardId=`${cardUrl}#carta`;const gameId=`${siteOrigin}/#forbidden-memories`;const faqId=`${cardUrl}#faq`;const datasetId=`${cardUrl}#dataset-drops`;
  const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${cardUrl}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:siteUrl("/")},{"@type":"ListItem",position:2,name:"Cartas",item:siteUrl("/cartas/")},{"@type":"ListItem",position:3,name:card.name,item:cardUrl}]},{"@type":"WebPage","@id":cardUrl,url:cardUrl,name:`${card.name}: drops, password e stats`,inLanguage:"pt-BR",mainEntity:{"@id":cardId},hasPart:[{"@id":datasetId},{"@id":faqId}]},{"@type":"Thing","@id":cardId,name:card.name,alternateName:card.namePt,description:card.summary,identifier:String(card.id),url:cardUrl,isPartOf:{"@id":gameId},additionalProperty:[{"@type":"PropertyValue",name:"ATK",value:card.atk},{"@type":"PropertyValue",name:"DEF",value:card.def},{"@type":"PropertyValue",name:"Password",value:card.password},{"@type":"PropertyValue",name:"Tipo",value:card.type},{"@type":"PropertyValue",name:"Atributo",value:card.attribute}]},{"@type":"VideoGame","@id":gameId,name:"Yu-Gi-Oh! Forbidden Memories",gamePlatform:"PlayStation",datePublished:"1999",sameAs:"https://yugipedia.com/wiki/Yu-Gi-Oh!_Forbidden_Memories"},{"@type":"Dataset","@id":datasetId,url:`${cardUrl}#drops`,name:`Drops de ${card.name} em Forbidden Memories`,description:`Personagens, ranks e probabilidades catalogadas para obter ${card.name}.`,dateModified,creator:datasetCreator,license:datasetLicense,isAccessibleForFree:true,about:{"@id":cardId},variableMeasured:["Duelista","Rank","Taxa de drop","Local"],hasPart:drops.map((_,i)=>`${cardUrl}#drop-${i+1}`)},{"@type":"FAQPage","@id":faqId,url:`${cardUrl}#curiosidades`,name:`Perguntas frequentes sobre ${card.name}`,inLanguage:"pt-BR",isPartOf:{"@id":cardUrl},about:{"@id":cardId},mainEntity:faq.map((item,i)=>({"@type":"Question","@id":`${faqId}-pergunta-${i+1}`,name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))}]};
  return <div className="exact-card-page">
    <header className="exact-header"><div className="exact-wrap exact-nav"><a className="exact-brand" href="/" aria-label="Yu-Gi-Oh! Forbidden Memories — início"><img className="exact-brand-logo" src="/logo.webp" alt="Yu-Gi-Oh! Forbidden Memories" width="346" height="112" decoding="async" /></a><nav className="exact-links"><a className="active" href="/cartas/">Cartas</a><a href="/drops/">Drops</a><a href="/mods/">Mods</a><a href="/passwords/">Passwords</a><a href="/guias/">Guias</a><a href="/blog/">Blog</a></nav><button className="exact-icobtn theme" aria-label="Tema" type="button">◐</button></div></header>
    <main className="exact-wrap">
      <div className="topbar"><nav className="crumb" aria-label="breadcrumb"><a href="/">Início</a><span className="sep">›</span><a href="/cartas/">Cartas</a><span className="sep">›</span><span className="cur">{card.name}</span></nav><div className="navbtns"><a className="nbtn" href={`/cartas/${previous.slug}/`}>‹ Voltar</a><a className="nbtn gold" href={`/cartas/${next.slug}/`}>Próxima ›</a></div></div>

      <div className="cardtop" id="visao"><div className="cardart">{cardImages[card.slug]?<img src={cardImages[card.slug]} alt={`Carta ${card.name} de Yu-Gi-Oh! Forbidden Memories`}/>:<CardVisual card={card}/>}</div><div className="cardmain"><h1>{card.name}</h1><div className="ptname">{card.namePt}</div><div className="badges"><span className="badge-c"><span className="dot">✶</span>{card.attribute}</span><span className="badge-c"><span className="dot">◈</span>{card.type}</span>{card.level>0&&<span className="badge-c lvl"><span className="dot">★</span>Nível {card.level}</span>}</div><p className="desc">{card.summary}</p><div className="quick"><b>Resposta rápida</b>O {card.name} (nº {String(card.id).padStart(3,"0")}) tem <strong>{card.atk} ATK</strong>, <strong>{card.def} DEF</strong> e password <strong>{card.password}</strong>. {drops.length?`Pode ser obtido por ${drops.map(drop=>drop.duelist).join(", ")}.`:"Os drops estão em validação."}</div><div className="statboxes"><div className="sbox atk"><div className="k">ATK</div><div className="v">{card.atk}</div></div><div className="sbox def"><div className="k">DEF</div><div className="v">{card.def}</div></div><div className="sbox sell"><div className="k">CUSTO EM ESTRELAS</div><div className="v">{card.price.toLocaleString("pt-BR")} <span className="coin">★</span></div></div></div></div><aside className="cardaside"><div className="id"><b>#{String(card.id).padStart(3,"0")}</b><span>Card ID no jogo</span></div><div className="aside-h">Como obter</div><div className="obtain"><div className="r"><span>Dropado</span><b>{drops.length?"Sim":"Em validação"}</b></div><div className="r"><span>Password</span><b>Sim</b></div><div className="r"><span>Troca</span><b>Sim</b></div></div><div className="aside-h">Raridade</div><div className="stars">★★★★★</div><div className="aside-h">Lançamento</div><div className="aside-launch">Yu-Gi-Oh! Forbidden Memories<br/>(PlayStation 1) — 1999</div></aside></div>

      <nav className="tabs" aria-label="Seções da carta"><a className="tab active" href="#visao">◈ Visão geral</a><a className="tab" href="#drops">⚔ Drops ({drops.length})</a><a className="tab" href="#passwords">◇ Passwords (1)</a><a className="tab" href="#precos">◉ Preços</a><a className="tab" href="#guia-completo">✦ Combinações</a><a className="tab" href="#curiosidades">𓂀 Curiosidades</a></nav>

      <section id="drops"><div className="sec-h"><h2>Quem <span>dropa</span> esta carta?</h2><a className="btn-ghost" href="/drops/">Ver todos os drops →</a></div><p className="sec-sub">Personagens que podem dropar {card.name}, ordenados por chance.</p>{drops.length?<div className="dropgrid">{drops.map((drop,i)=>{const duelistSlug=drop.duelistSlug||taxonomySlug(drop.duelist);const portrait=duelistsBySlug.get(duelistSlug)?.squareImage;return <a id={`drop-${i+1}`} className="dropcard" href={`/drops/${duelistSlug}/`} key={`${drop.duelist}-${drop.rate}`} aria-label={`Ver todos os drops de ${drop.duelist}`}><div className={`portrait portrait-${i%5}`}>{portrait?<img src={portrait} alt={drop.duelist} loading="lazy"/>:<div className="mono">{drop.duelist.charAt(0)}</div>}<div className="nm">{drop.duelist}</div></div><div className="rows"><div className="rw"><span>Taxa de Drop</span><span className="rate">{drop.rate}</span></div><div className="rw"><span>Rank</span><span className="val">{drop.pool}</span></div><div className="rw"><span>Local</span><span className="val">{drop.location}</span></div></div></a>})}</div>:<div className="detail-empty"><b>Dados em validação</b><p>Os drops serão exibidos após a validação do dataset.</p></div>}<div className="note"><span className="i">ⓘ</span> As taxas podem variar conforme a sorte e o desempenho no duelo.</div></section>

      <section id="passwords"><div className="sec-h"><h2>Password da <span>carta</span></h2><a className="btn-ghost" href="/passwords/">Ver todos os passwords →</a></div><p className="sec-sub">Use na opção Password do jogo para localizar a carta.</p><div className="pwblock"><span className="pwtag">Password</span><span className="pwcode">{formattedPassword}</span><span className="pwplat">Funciona em ◈ PS1</span><CopyPassword code={card.password}/></div></section>

      <section id="precos"><div className="sec-h"><h2>Preços e <span>onde comprar</span></h2></div><p className="sec-sub">Valores baseados no sistema de estrelas do jogo.</p><div className="pricegrid"><div className="pcard hl"><div className="lab">Custo por password</div><div className="bigprice"><span className="coin">★</span>{card.price.toLocaleString("pt-BR")}<small>estrelas</small></div></div><div className="pcard"><div className="lab">Como obter</div><div className="shoprow"><span>Password</span><b>Disponível</b></div><div className="shoprow"><span>Drop</span><b>{drops.length?"Catalogado":"Em validação"}</b></div><div className="shoprow"><span>Troca</span><b>Disponível</b></div></div><div className="pcard"><div className="lab">Dica</div><p className="tip">Compare o custo em estrelas com o tempo estimado de farm antes de escolher como obter esta carta.</p></div></div></section>

      <div className="detwrap"><div className="detgrid"><div className="det"><h4>Categoria da carta</h4><span className="pill">{card.type}</span></div><div className="det"><h4>Descrição (resumo)</h4><p>{card.summary}</p></div><div className="det"><h4>ID da carta</h4><p>{card.id}</p></div><div className="det"><h4>Atributo</h4><a className="lnk" href={`/cartas/?busca=${encodeURIComponent(card.attribute)}`}>{card.attribute} →</a></div></div></div>

      {related.length>0&&<section id="relacionadas"><div className="sec-h"><h2>Cartas <span>relacionadas</span></h2></div><div className="relrow">{related.map(item=><a className="relcard" href={`/cartas/${item.slug}/`} key={item.slug}><div className="pic">{cardImages[item.slug]?<img src={cardImages[item.slug]} alt={item.name}/>:<CardVisual card={item} compact/>}</div><div className="rn">{item.name}</div><div className="ratk"><span>{item.attribute}</span><b>{item.atk}</b></div></a>)}</div></section>}

      <article className="seo-guide" id="guia-completo"><header><small>CONTEÚDO SEO · AEO · GEO</small><h2>Guia completo: como conseguir <span>{card.name}</span></h2><p className="guide-definition"><strong>{card.name}</strong> ({card.namePt}) é uma carta do tipo {card.type}, atributo {card.attribute}, com {card.atk} de ATK e {card.def} de DEF em Yu-Gi-Oh! Forbidden Memories.</p><p className="guide-updated">Atualizado em <time dateTime={dateModified}>18 de agosto de 2026</time></p></header><nav aria-label="Índice do guia"><b>Neste guia</b><a href="#o-que-e">O que é?</a><a href="#como-conseguir">Como conseguir?</a><a href="#vale-a-pena">Vale a pena?</a><a href="#dados-carta">Dados completos</a></nav><div className="guide-copy"><section id="o-que-e"><h3>O que é {card.name} em Forbidden Memories?</h3><p>{card.summary} Seu nome em português é <strong>{card.namePt}</strong>, e seu ID é #{String(card.id).padStart(3,"0")}.</p></section><section id="como-conseguir"><h3>Como conseguir {card.name}?</h3><p>{drops.length?`A carta pode ser obtida com ${drops.map(drop=>drop.duelist).join(", ")}. O password é ${card.password}, com custo de ${card.price.toLocaleString("pt-BR")} estrelas.`:`O password é ${card.password}. Os drops ainda estão em validação.`}</p></section><section id="vale-a-pena"><h3>Vale a pena usar {card.name} no deck?</h3><p>{card.atk>=2500?`Com ${card.atk} de ATK, oferece alto poder ofensivo para decks de ${card.type}.`:`A utilidade depende das fusões e da sinergia com cartas de ${card.type}.`} Compare custo e tempo de farm.</p></section><section id="dados-carta"><h3>Quais são os dados completos da carta?</h3><div className="guide-table-wrap"><table><caption>Ficha de {card.name}</caption><thead><tr><th>Informação</th><th>Valor</th></tr></thead><tbody><tr><th>ID</th><td>{card.id}</td></tr><tr><th>Tipo</th><td>{card.type}</td></tr><tr><th>Atributo</th><td>{card.attribute}</td></tr><tr><th>Nível</th><td>{card.level||"Não se aplica"}</td></tr><tr><th>ATK / DEF</th><td>{card.atk} / {card.def}</td></tr><tr><th>Password</th><td>{card.password}</td></tr></tbody></table></div></section></div></article>

      <section id="curiosidades" className="faq-exact"><div className="sec-h"><h2>Perguntas <span>frequentes</span></h2></div><div className="faq-exact-list">{faq.map((item,i)=><details open={i===0} key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>
    </main>
    <footer className="exact-footer"><div className="exact-wrap"><span>Yu-Gi-Oh! Forbidden Memories — banco de dados e guias em português.</span><span><b>▲</b> O site não hospeda arquivos. Apenas indexamos links externos.</span></div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  </div>
}
